# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://SWaiter.github.io
date_format: "ordinal"
title: 码的世界
subtitle: "分享简单的快乐"
description: "王闪的个人博客"
keywords: code, Wang Shan, Swaiter
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Wang Shan
organization: wangshan@yoozoo.com
organization_url: https://SWaiter.github.io
github_username: SWaiter
location: ShangHai, China
email: 787324413@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: SWaiter.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: SWaiter.github.io
    repo: blog-comments
    oauth:
        client_id: 8318b75f3ca8a3170fed
        client_secret: 31ecc84845afec969617435f0b83d71798135648
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: SWaiter.github.io
    repo: blog-comments
    clientID: 8318b75f3ca8a3170fed
    clientSecret: 31ecc84845afec969617435f0b83d71798135648
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
